name: Artifact
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: myArtifact
    steps:
    - name: Checout Code
      uses: actions/checkout@v2.4.2
    - name: Upload the rrtifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
      



